main: me.infinityz.minigame.UHC
name: UHC-1.16
version: 0.5D
description: "Redundant and optimized UHC minigame plugin."
api-version: "1.16"
api: "1.16"
authors: [infinityz, aleiv]
softdepend: [Kern, Chunky, Vault, Citizens]
